import { StyleSheet } from 'react-native';
import { Typography } from '../../../../constants/Typography';

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerContainer: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 4,
  },
  headerBar: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    height: 36,
  },
  dismissBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  centerContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  shieldBox: {
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: 8,
    borderWidth: 1,
  },
  title: {
    fontSize: 19,
    fontWeight: '700',
    fontFamily: Typography.fontFamily,
    marginBottom: 4,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 13,
    textAlign: 'center',
    marginHorizontal: 16,
    fontFamily: Typography.fontFamily,
    lineHeight: 18,
    marginBottom: 6,
  },
  dotsRow: {
    flexDirection: 'row',
    gap: 14,
    marginVertical: 10,
    alignSelf: 'center',
  },
  dot: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 2,
  },
  errorText: {
    color: '#dc2626',
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 4,
    textAlign: 'center',
    fontFamily: Typography.fontFamily,
  },
  keypadContainer: {
    width: '100%',
    maxWidth: 270,
    marginTop: 4,
    alignSelf: 'center',
  },
  keypadRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
    width: '100%',
  },
  keyContainer: {
    width: 62,
    height: 62,
    borderRadius: 31,
  },
  key: {
    width: 62,
    height: 62,
    borderRadius: 31,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  keyDigit: {
    fontSize: 24,
    fontWeight: '600',
    fontFamily: Typography.fontFamily,
  },
  skipButton: {
    marginTop: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  skipButtonText: {
    fontSize: 13,
    fontWeight: '600',
    fontFamily: Typography.fontFamily,
  },
});
