import { AttachmentOptionItem } from './types';

export const ATTACHMENT_OPTIONS: AttachmentOptionItem[] = [
  {
    key: 'media',
    title: 'Photos & videos',
    description: 'Send listing media and clips',
    icon: 'videocam-outline',
    lightBg: '#eaf5e8',
    darkBg: '#142918',
    lightColor: '#2f9b5f',
    darkColor: '#4ade80',
  },
  {
    key: 'document',
    title: 'Documents',
    description: 'Share brochures, PDFs & contracts',
    icon: 'document-text-outline',
    lightBg: '#efeafe',
    darkBg: '#241a3c',
    lightColor: '#7a55d8',
    darkColor: '#a78bfa',
  },
  {
    key: 'catalog',
    title: 'Catalog',
    description: 'Attach property from listings',
    icon: 'home-outline',
    lightBg: '#fdf3e7',
    darkBg: '#36210f',
    lightColor: '#d97706',
    darkColor: '#fbbf24',
  },
  {
    key: 'form',
    title: 'Send Form',
    description: 'Insert custom inquiry form',
    icon: 'calendar-outline',
    lightBg: '#fdf6f8',
    darkBg: '#2b0d16',
    lightColor: '#4a0f1f',
    darkColor: '#f472b6',
  },
  {
    key: 'lead',
    title: 'Create lead',
    description: 'Capture a new contact from chat',
    icon: 'person-add-outline',
    lightBg: '#f6ebee',
    darkBg: '#2b0d16',
    lightColor: '#4a0f1f',
    darkColor: '#f472b6',
  },
  {
    key: 'assign-agent',
    title: 'Assign Agent',
    description: 'Delegate to a team agent',
    icon: 'people-outline',
    lightBg: '#eaf0fb',
    darkBg: '#152338',
    lightColor: '#4a6b9a',
    darkColor: '#60a5fa',
  },
  {
    key: 'embed',
    title: '3D Tour / Embed code',
    description: 'Paste iframe or viewer URL',
    icon: 'cube-outline',
    lightBg: '#eaf0fb',
    darkBg: '#152338',
    lightColor: '#4a6b9a',
    darkColor: '#60a5fa',
  },
];
