import { StyleSheet } from 'react-native';
import { Typography } from '../../../constants/Typography';

export const styles = StyleSheet.create({
  subTabsRow: { flexDirection: 'row', paddingHorizontal: 16, borderBottomWidth: 1 },
  subTabBtn: { paddingVertical: 10, marginRight: 20 },
  subTabText: { fontSize: 13, fontFamily: Typography.fontFamily },
  filterScroll: { flexDirection: 'row', gap: 8, paddingHorizontal: 16, paddingVertical: 8 },
  filterChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: 'rgba(128,128,128,0.12)',
  },
  filterChipText: {
    fontSize: Typography.sizes.xs,
    fontFamily: Typography.fontFamily,
    fontWeight: '600',
  },
  centerContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 32,
    paddingTop: 60,
  },
  emptyTitle: {
    fontSize: Typography.sizes.md,
    fontWeight: '700',
    fontFamily: Typography.fontFamily,
    marginTop: 14,
  },
  emptySubtitle: {
    fontSize: Typography.sizes.sm,
    fontFamily: Typography.fontFamily,
    textAlign: 'center',
    marginTop: 6,
    lineHeight: 20,
  },
  card: { borderRadius: 16, borderWidth: 1, padding: 14, marginBottom: 12 },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  cardTitle: { fontSize: 15, fontWeight: '700', fontFamily: Typography.fontFamily },
  statusPill: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 10 },
  statusPillText: { fontSize: 10, fontWeight: '700', fontFamily: Typography.fontFamily },
  sourcePill: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 10 },
  sourcePillText: { fontSize: 10, fontWeight: '700', fontFamily: Typography.fontFamily },
  cardMeta: { fontSize: 12, marginTop: 4, fontFamily: Typography.fontFamily },
  cardNote: { fontSize: 12, marginTop: 6, lineHeight: 16, fontFamily: Typography.fontFamily },
  openChatBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
  },
  openChatBtnText: { fontSize: 11, fontWeight: '700', fontFamily: Typography.fontFamily },
  setStatusRow: {
    marginTop: 12,
    paddingTop: 10,
    borderTopWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  setStatusLabel: { fontSize: 10, fontWeight: '700', fontFamily: Typography.fontFamily },
  setStageBtn: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 10, borderWidth: 1 },
  setStageBtnText: { fontSize: 11, fontWeight: '600', fontFamily: Typography.fontFamily },
  timestampText: { fontSize: 10, marginTop: 8, fontFamily: Typography.fontFamily },
  masterLeadBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    borderWidth: 1,
  },
  masterLeadBadgeText: {
    fontSize: 9.5,
    fontWeight: '700',
    letterSpacing: 0.5,
    fontFamily: Typography.fontFamily,
  },
  unassignedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    borderWidth: 1,
  },
  unassignedBadgeText: { fontSize: 9.5, fontWeight: '700', fontFamily: Typography.fontFamily },
  selfAssignedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    borderWidth: 1,
  },
  selfAssignedBadgeText: { fontSize: 9.5, fontWeight: '700', fontFamily: Typography.fontFamily },
  assignedAgentChip: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    marginTop: 6,
  },
  agentInitialsCircle: {
    width: 16,
    height: 16,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 6,
  },
  agentInitialsText: { color: '#ffffff', fontSize: 8.5, fontWeight: '700' },
  assignedAgentName: { fontSize: 11, fontWeight: '600', fontFamily: Typography.fontFamily },
  listingTitleText: { fontSize: 11.5, fontWeight: '500', fontFamily: Typography.fontFamily },
});
