import { StyleSheet } from 'react-native';
import { Typography } from '../../../constants/Typography';

export const styles = StyleSheet.create({
  backdrop: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.65)', justifyContent: 'flex-end' },
  keyboardAvoid: { width: '100%', justifyContent: 'flex-end' },
  card: { width: '100%', maxHeight: '85%', borderTopLeftRadius: 24, borderTopRightRadius: 24, borderWidth: 1, borderBottomWidth: 0, overflow: 'hidden' },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 18, paddingVertical: 14, borderBottomWidth: StyleSheet.hairlineWidth },
  headerTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  sparkleBadge: { width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  headerTitle: { fontSize: 16, fontWeight: '700', fontFamily: Typography.fontFamily },
  headerSubtitle: { fontSize: 12, fontFamily: Typography.fontFamily, marginTop: 1 },
  closeBtn: { padding: 6 },
  scrollBody: { maxHeight: 520 },
  scrollContent: { padding: 16, gap: 14 },
  contextBox: { padding: 12, borderRadius: 12, borderWidth: 1 },
  contextLabel: { fontSize: 11, fontWeight: '700', fontFamily: Typography.fontFamily, marginBottom: 4, textTransform: 'uppercase' },
  contextText: { fontSize: 13, fontFamily: Typography.fontFamily, fontStyle: 'italic', lineHeight: 18 },
  sectionTitle: { fontSize: 12, fontWeight: '600', fontFamily: Typography.fontFamily, textTransform: 'uppercase', letterSpacing: 0.5 },
  chipsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: { flexDirection: 'row', alignItems: 'center', paddingVertical: 7, paddingHorizontal: 12, borderRadius: 20, borderWidth: 1 },
  chipText: { fontSize: 12, fontWeight: '600', fontFamily: Typography.fontFamily },
  customInputRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  customInput: { flex: 1, height: 42, borderRadius: 21, borderWidth: 1, paddingHorizontal: 16, fontSize: 14, fontFamily: Typography.fontFamily },
  sendBtn: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center' },
  loadingBox: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, paddingVertical: 14 },
  loadingText: { fontSize: 13, fontFamily: Typography.fontFamily },
  responseCard: { borderRadius: 16, padding: 14, borderWidth: 1, gap: 10 },
  responseHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  responseHeaderTitle: { fontSize: 12, fontWeight: '700', fontFamily: Typography.fontFamily, textTransform: 'uppercase' },
  responseText: { fontSize: 14, lineHeight: 21, fontFamily: Typography.fontFamily },
  insertBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 10, paddingHorizontal: 16, borderRadius: 10, marginTop: 4 },
  insertBtnText: { color: '#ffffff', fontSize: 13, fontWeight: '600', fontFamily: Typography.fontFamily },
});
